'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Microsoft.VisualStudio.TestTools.WebTesting
Imports Microsoft.VisualStudio.TestTools.WebTesting.Rules
Imports System
Imports System.Collections.Generic
Imports System.Text

Namespace WebAndLoadTestProject1

    Public Class WebTest1Coded
        Inherits ThreadedWebTest

        Public Sub New()
            MyBase.New
            Me.PreAuthenticate = true
            Me.Proxy = "default"
        End Sub

        Public Overrides Sub Run()
            Dim conditionalRule1 As ForLoopRule = New ForLoopRule()
            conditionalRule1.ContextParameterName = "i"
            conditionalRule1.ComparisonOperator = ForLoopComparisonOperator.LessThan
            conditionalRule1.TerminatingValue = 100R
            conditionalRule1.InitialValue = 0R
            conditionalRule1.IncrementValue = 1R

            Dim maxIterations1 As Integer = -1
            Dim advanceDataCursors1 As Boolean = false
            Me.BeginLoop(conditionalRule1, maxIterations1, advanceDataCursors1)

            Do While Me.ExecuteConditionalRule(conditionalRule1)
                Dim request1 As WebTestRequest = New WebTestRequest("http://hytest.taiji-sun.com/")
                request1.Encoding = System.Text.Encoding.GetEncoding("utf-8")
                MyBase.Send(request1)
                request1 = Nothing

            Loop

            Me.EndLoop(conditionalRule1)
        End Sub
    End Class
End Namespace
